### ISSUE TITLE
Navigation groups order with collapsible state

### ISSUE THREAD

**Issue by mikemastercorp** [laravel-filament/demo#106]
Hello. I've been trying to get the filament navigation groups I've created to get ordered in the desired way, however I also wanted to be able to set some groups as collapsed and other non-collapsed.

I know how to sort the navigation groups in AdminPanelProvider.php however in your example you are simply listing the navigation groups in the desired order letting them all to be collapsed. How should I modify the code to make let's say Blog group open and Shop group closed...

<pre>
->navigationGroups([
    'Shop',
     'Blog',
 ])
</pre>

Also, I've attempted to define an icon for a navigation group while having defined icons for the items inside the group and I got a warning that I have the right to either add an icon on the navigation group or the items inside. The explanation was to avoid confusion, however most nowadays admins allow the group as well as the items inside to have an icon that is sometimes facilitating the options understanding from the first look. Can you elaborate on the idea of this limitation?

**Comment by pxlrbt** [comment]
Hey, this is the issue tracker for the demo repository. Please post question either on our Discord or in the [Discussion section of the filament/filament repo](https://github.com/filamentphp/filament/discussions). Thanks.
