### ISSUE TITLE
Undefined variable $getSelectedRecordCount vendor/filament/tables/resources/views/index.blade.php

### ISSUE THREAD

**Issue by sayasuhendra** [laravel-filament/demo#11]
![image](https://user-images.githubusercontent.com/4870292/147527637-780ec285-29cc-4fb2-8f5a-c0246f8f669b.png)

**Comment by ManojKiranA** [comment]
have you changed anything

**Comment by sayasuhendra** [comment]
I haven't made any change. After doing git pull i got this issue.

Before it's running. No git conflict when I'm running git pull. 

I have run php artisan migrate:fresh --seed

**Comment by sayasuhendra** [comment]
when I clone again, there is no issue. maybe better i close this issue.
