### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by suhaimim** [laravel-filament/demo#33]
![tmperr](https://user-images.githubusercontent.com/35832684/176995599-0d061f6b-4acd-4a3f-bfc7-5ccb7cb634fd.png)

**Comment by pxlrbt** [comment]
I just tried to reproduce this, but installation with the steps from the docs works fine here. Is this really a fresh clone? Is this error coming after `composer install`?

**Comment by basiima** [comment]
Fix:

On Ubuntu
1. Open the terminal
2. Type command "sudo apt-get install -y php-intl"

On Windows
1. Stop Xampp or Wamp
2. Open the xampp/php/php.ini file in editor
3. Remove starting semicolon(;) from (;extension=php_intl.dll)
4. Restart Xampp or Wamp

**Comment by zepfietje** [comment]
Closing as inactive.
