### ISSUE TITLE
What license does this repository fall under? The license file is missing.

### ISSUE THREAD

**Issue by emmadesilva** [laravel-filament/demo#39]
This demo is very well designed, and it would be neat to be able to use components from it. However, since there is no license file attached, no-one is allowed to use the code herein. https://choosealicense.com/no-permission/

I would suggest the MIT License, as that's what both Laravel and FilamentPHP uses.

All the best, Caen

**Comment by pxlrbt** [comment]
Added the MIT license as the main repo.

**Comment by emmadesilva** [comment]
Awesome, thanks!
