### ISSUE TITLE
Demo 503 Error code

### ISSUE THREAD

**Issue by blite** [laravel-filament/demo#43]
<img width="892" alt="Screen Shot 2022-08-01 at 10 50 54 AM" src="https://user-images.githubusercontent.com/442226/182211142-c89778e6-169a-4b6a-86e8-ed353d28a4f3.png">

I have actually seen this a few times before. I assumed maybe it was a rate limit.  Probably someone is currently updating it, but might be worth exploring if it can deployed with less downtime?

**Comment by pxlrbt** [comment]
The demo is refreshed regularly by reseeding the DB. This takes some time, as we also generate images during the seeding.
Not sure how long the exact downtime is.

**Comment by pxlrbt** [comment]
Looks like it might be an actual issue this time

**Comment by blite** [comment]
seems back up, closing this
