### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 no such table: currencies 

### ISSUE THREAD

**Issue by stephanus-tantiono** [laravel-filament/demo#44]
got this error when trying to setup the demo at my local 

https://flareapp.io/share/x5My0Xe5#F140

**Comment by stephanus-tantiono** [comment]
already do the migration and seed, also composer update

**Comment by danharrin** [comment]
Make sure your PHP server has the `sqlite` extension

**Comment by qcol** [comment]
I have the same thing. It happens on both MySql and sqlite engine. Currencies table is missing. 

![image](https://user-images.githubusercontent.com/358993/213511736-b3bbefe7-47ae-4104-b49d-3a6d2d03cf49.png)

**Comment by danharrin** [comment]
Currencies are stored in an in-memory database, not your projects database

**Comment by qcol** [comment]
OK, I understand. In any case, I have the same error :

![image](https://user-images.githubusercontent.com/358993/213552384-9ea53030-daa8-40a5-895c-ec6884a0ed0f.png)

**Comment by pxlrbt** [comment]
> OK, I understand. In any case, I have the same error :
> 
> ![image](https://user-images.githubusercontent.com/358993/213552384-9ea53030-daa8-40a5-895c-ec6884a0ed0f.png)

Do you have SQLite installed?

**Comment by qcol** [comment]
yes, SQLite installed

**Comment by joleenshook** [comment]
I am getting this as well with both MySQL and SqlLite.  Fresh install from Github today.

**Comment by agussuhartono** [comment]
Hi, 
This error occurred on "squirephp".
Squirephp use Sqlite mem to store information.

first, please double check that you have the sqlite3 and pdo_sqlite PHP extensions installed. To do this, you could dd(extension_loaded('sqlite3'), extension_loaded('pdo_sqlite')); and check that it outputs "true", "true".

next, delete file "storage/framework/cache/squire-squire-models-country-en.sqlite" and "storage/framework/cache/squire-squire-models-currency-en.sqlite"

reference :  

https://github.com/squirephp/squire/discussions/13
