### ISSUE TITLE
Unable to save product with image

### ISSUE THREAD

**Issue by bj32161** [laravel-filament/demo#45]
Hi there,
On product edit page. after I uploaded image when I click save the image is gone (only show file name not image). What I'm missing?
Thanks
Panya
![after-click-save](https://user-images.githubusercontent.com/7337058/184054811-cb2de0b4-c8c5-4739-b21e-e700d5c2bda2.png)
![uploaded](https://user-images.githubusercontent.com/7337058/184054824-2432e724-fd7a-4db1-8326-10fc357b0f3b.png)

**Comment by danharrin** [comment]
Hey, have you set this up locally or something?

https://filamentphp.com/tricks/file-upload-previews-not-loading
