### ISSUE TITLE
Demo images missing?

### ISSUE THREAD

**Issue by emmadesilva** [laravel-filament/demo#51]
Aren't there supposed to be images on this page? https://demo.filamentphp.com/blog/posts. Same on the products page.

![image](https://user-images.githubusercontent.com/95144705/194751576-c274dbcd-e3ec-4e7a-a867-2d27a50591be.png)

**Comment by zepfietje** [comment]
I'm not sure if they're seeded.
Also, I just tried to upload an image, and while it saved successfully, it was not persisted.

@shuvroroy, any idea?

**Comment by emmadesilva** [comment]
> Also, I just tried to upload an image, and while it saved successfully, it was not persisted.

Hmm, weird. I could upload an image, and it seems it's persisted on my end after refreshing. https://demo.filamentphp.com/blog/posts/1/edit

**Comment by zepfietje** [comment]
Oh, it works for me too now. Weird.

Anyway, I think it's just a seeder missing?

**Comment by emmadesilva** [comment]
> Oh, it works for me too now. Weird.
> 
> Anyway, I think it's just a seeder missing?

You're probably right. The [`DatabaseSeeder#L29`](https://github.com/filamentphp/demo/blob/main/database/seeders/DatabaseSeeder.php#L29) has a task to delete images, but I'm not seeing where the default ones get added.

**Comment by zepfietje** [comment]
Feel free to PR, @caendesilva. 🙂

**Comment by emmadesilva** [comment]
> Feel free to PR, @caendesilva. 🙂

I would but I actually have no idea what the problem is. I think this is best managed by the one managing the site, as I'm fairly sure this used to work.

**Comment by zepfietje** [comment]
I don't think it actually had an image seeder, though not sure.

**Comment by zepfietje** [comment]
@danharrin confirm?

**Comment by shuvroroy** [comment]
@zepfietje and @caendesilva Issue fixed now. Please check

**Comment by shuvroroy** [comment]
Thanks for reporting this @caendesilva. I gave a fix for that issue.

**Comment by zepfietje** [comment]
Oh so it actually was a broken image provider. Thanks for fixing, @shuvroroy!

**Comment by emmadesilva** [comment]
> Thanks for reporting this @caendesilva. I gave a fix for that issue.

Awesome! Looks great!
