### ISSUE TITLE
Incorrect DateTime Format for App/Models/Shop/Product insert into comments created_at when using mySQL instead of sqlite

### ISSUE THREAD

**Issue by andrewdwallo** [laravel-filament/demo#54]
Just wanted to let ya'll know that when using mySQL instead of sqlite there is an error after running "php artisan db:seed" for this.. 
It works when I set config/database mysql strict=false, but otherwise it won't work. Don't know if you want to fix that or just tell the users who use mySQL instead to set that in config/database.. might lead to incorrect formats though when doing that. Also it's impossible to use this unless you enable pdo_sqlite extension in php.ini, some people who don't want to use sqlite and instead use mysql will have an error whenever they want to use the "composer install, composer require, or composer update" command... unless they want to use "--ignore-platform-req=ext-pdo_sqlite" at the end of every single composer command. Might want to let those people know this as well.

**Comment by zepfietje** [comment]
Hey @andrewdwallo, thanks for reporting!
I don't think we're doing anything non-default Laravel here, right?

**Comment by pxlrbt** [comment]
Not sure about the date issue. I also experienced issues during seeding because of timezone differences. Wasn't sure how to eliminate this though with the seeder. 

I think `ext-pdo_sqlite` is required for `squire`, so I am not sure how it helps if you install it without sqlite enabled.

**Comment by andrewdwallo** [comment]
Everything worked correctly even without sqlite enabled. I'm not sure what squire is but I didn't seem to have any issues even though sqlite is supposedly required for squire to work.

**Comment by mszabeh** [comment]
` SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2022-03-22 00:58:30' for column 'created_at' at row 1 (SQL: insert into `shop_orders` (`number`, `currency`, `total_price`, `status`, `shipping_price`, `shipping_method`, `notes`, `created_at`, `updated_at`, `shop_customer_id`) values (OR26157, bsd, 1247.57, delivered, 461.13, flat, Yet you turned a back-somersault in at the end.' 'If you can't be Mabel, for I know I do!' said., 2022-03-22 00:58:30, 2022-08-12 14:00:54, 863))`

**Comment by zepfietje** [comment]
@pxlrbt is there anything we should do here? Or just tell people to use MySQL?

**Comment by andrewdwallo** [comment]
I had the error when using MySQL... I think the error is because the demo requires squire which uses sqlite and I guess squire's datetime format for this is wrong if you are using MySQL instead of sqlite... but idk I never use sqlite and/or squire.

**Comment by pxlrbt** [comment]
@zepfietje Not sure about that latest issue. The original issue was timezone conversion resulting in invalid dates because the day was rolling over on the last day of February. 

`2022-03-22 00:58:30 ` seems like a valid date to me 🤔

**Comment by zepfietje** [comment]
So anything to be done on the initial bug report then?

**Comment by pxlrbt** [comment]
Probably the same issue. Not sure though, because it doesn't include the whole error.

**Comment by mszabeh** [comment]
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2022-03-22 00:43:55' for column 'created_at' at row 1 (SQL: insert into `shop_payments` (`reference`, `currency`, `amount`, `provider`, `method`, `created_at`, `updated_at`, `order_id`) values (PAY257686, YER, 1530.66, paypal, bank_transfer, 2022-03-22 00:43:55, 2022-07-11 23:55:52, 561))

**Comment by andrewdwallo** [comment]
> Probably the same issue. Not sure though, because it doesn't include the whole error.

Maybe using INNO_DB engine on the tables will resolve the errors but I haven't tested anything since my original issue that I posted so Idk

**Comment by mszabeh** [comment]
I could run
`php artisan migrate:refresh --seed`
when using mySQL
with 
`created_at' => $this->faker->dateTimeBetween('-5 month', '-1 month'),`

istead of

`'created_at' => $this->faker->dateTimeBetween('-1 year', 'now'),`

**Comment by qcol** [comment]
In my case it helped to set  the connection offset to +00:00 in  config/database.php:

```
'mysql' => [
            'driver' => 'mysql',
            ...
            'timezone'  => '+00:00',
        ],
```

Seed passes without errors, but after starting the application I get an error - no currencies table

**Comment by zepfietje** [comment]
> I could run `php artisan migrate:refresh --seed` when using mySQL with `created_at' => $this->faker->dateTimeBetween('-5 month', '-1 month'),`
> 
> istead of
> 
> `'created_at' => $this->faker->dateTimeBetween('-1 year', 'now'),`

How exactly would this be a fix to the issue? 🙂

**Comment by zepfietje** [comment]
Closing this, but feel free to comment with reliable reproduction steps or PR a fix. 😄
