### ISSUE TITLE
total price not update

### ISSUE THREAD

**Issue by mszabeh** [laravel-filament/demo#56]
when you create a new order
or edit order
total_price not update after order saved

**Comment by scoba6** [comment]
I see the same issue and looking for a solution, because i use this feature in one of my apps based on filament. Someone to help me? Thx a lot

**Comment by jason-beach** [comment]
I'd really like to see an example of this in the demo b/c I think it would be helpful with a similar functionality within my app. Thanks!

**Comment by kostopravby** [comment]
totally agree. I need this example too.

**Comment by zepfietje** [comment]
Currently the order `total_price` is just a random seeded value that doesn't make sense if you add up the price of all order items. Probably you'd want a realtime value (maybe an accessor on the order model) that's always up-to-date.

I'm closing this issue now, but feel free to PR a proper implementation as outlined above. 🙂
