### ISSUE TITLE
Are there any alternative packages?

### ISSUE THREAD

**Issue by Odilbukh** [laravel-filament/demo#58]
Are there any alternative packages for "squirephp/currencies-en" and "squirephp/countries-en" ?

**Comment by Odilbukh** [comment]
![image](https://user-images.githubusercontent.com/22895615/217476448-bafe98b2-2295-4b22-ab5f-9bfbcd0285a4.png)

**Comment by zepfietje** [comment]
Could you try deleting your `composer.lock` file and running `composer install` again?
