### ISSUE TITLE
created_at and updated_at columns at pivot table are not filled automatically

### ISSUE THREAD

**Issue by umardy** [laravel-filament/demo#60]
When I add category in product's categories field, it shows normally, but in the shop_category_product, created_at and updated_at column are not filled automatically. These behavior also happened in couple of my filament project that use pivot table, not just on this demo.

<img width="1095" alt="Screenshot 2023-02-25 at 09 58 07" src="https://user-images.githubusercontent.com/41959863/221332747-5b0de2de-a859-45ec-928c-b078ecdcd3a1.png">

<img width="746" alt="Screenshot 2023-02-25 at 09 48 11" src="https://user-images.githubusercontent.com/41959863/221332755-c6ae2fa0-7eaf-4fc0-9fe6-e493f542913c.png">

**Comment by shuvroroy** [comment]
@umardy Thanks 🙇 . Issue fixed
