### ISSUE TITLE
500 error creating order

### ISSUE THREAD

**Issue by tonypartridge** [laravel-filament/demo#63]
eileenme raised it on discord, confirmed error on live demo.

When creating an order on demo https://demo.filamentphp.com/shop/orders/create there is an server error. I run on my side that the error shows:
Call to a member function address() on null

More info:
App \ Forms \ Components\ AddressForm: 26
saveRelationships

$relationship = $record->{$this->getRelationship()}();

**Comment by zepfietje** [comment]
Don't really like the current code, but this should fix the error at least: https://github.com/filamentphp/demo/commit/45cb6d386ea4e110b9b5529ba50444b94579d551.
