### ISSUE TITLE
DB seed error message

### ISSUE THREAD

**Issue by mai1237** [laravel-filament/demo#68]
Using MySql i got the message below
Creating shop products...
 16/50 [========>-------------------]  32%
   Illuminate\Database\QueryException

  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2023-03-26 03:21:04' for column `abc_abcb_b10`.`shop_products`.`updated_at` at row 1 (SQL: insert into `shop_products` (`name`, `slug`, `sku`, `barcode`, `description`, `qty`, `security_stock`, `featured`, `is_visible`, `old_price`, `price`, `cost`, `type`, `published_at`, `created_at`, `updated_at`, `shop_brand_id`) values (Cross-group demand-driven synergy, cross-group-demand-driven-synergy, 53728579, 0258279495410, Alice desperately: 'he's perfectly idiotic!' And she squeezed herself up and leave the court; but on second thoughts she decided on going into the air off all its feet at the Cat's head with great., 5, 5, 1, 1, 440.86, 339.05, 106, downloadable, 2022-10-05 01:56:12, 2022-10-19 00:59:44, 2023-03-26 03:21:04, 177))

**Comment by mnurullahsaglam** [comment]
Please have a look at the README.md file. just above "Features to explore" title, there is a warning which is down below.

> **Note**  
> If you get an "Invalid datetime format (1292)" error, this is probably related to the timezone setting of your database.  
> Please see https://dba.stackexchange.com/questions/234270/incorrect-datetime-value-mysql
