### ISSUE TITLE
small bugs in demo or core?

### ISSUE THREAD

**Issue by EvodiaAut** [laravel-filament/demo#73]
* If you delete more than 2 order items its generate blank order items
https://demo.filamentphp.com/shop/orders/1/edit
* If you finish to sort a brand he start random shuffling for all brands?
https://demo.filamentphp.com/shop/brands

**Comment by EvodiaAut** [comment]
https://github.com/livewire/livewire/pull/6289

**Comment by EvodiaAut** [comment]
✅ **Solved:**
If you delete more than 2 order items its generate blank order items

🐞 **Open:** 
If you finish to sort a brand he start random shuffling for all brands?
https://demo.filamentphp.com/shop/brands?isTableReordering=true

**Comment by zepfietje** [comment]
Please open an issue on the main Filament repo, @EvodiaAut.

**Comment by EvodiaAut** [comment]
@zepfietje ✅  https://github.com/filamentphp/filament/issues/7873
But the bot close the issue maybe you can open?

**Comment by zepfietje** [comment]
@pxlrbt has done that for you. 👍
