### ISSUE TITLE
Option has small glitch.

### ISSUE THREAD

**Issue by DevVerma07** [laravel-filament/demo#76]
Select::make('freelancer_id')
->label('Freelancer')
->options(Freelancer::all()->pluck('user.name', 'user_id'))
->searchable()->required(),
[![image](https://www.linkpicture.com/q/Screenshot-from-2023-08-18-13-27-50.png)](https://www.linkpicture.com/view.php?img=LPic64df2521da8011208428278)
in this form, if we reload, It has a small white color dropdown arrow glitch in dark mode

**Comment by DevVerma07** [comment]
please solve it

**Comment by zepfietje** [comment]
Please report issues on the main Filament repo.
