### ISSUE TITLE
error run demo using ubuntu 18

### ISSUE THREAD

**Issue by gitcoffee** [laravel-filament/demo#79]
![Captura de pantalla de 2023-08-23 16-39-06](https://github.com/filamentphp/demo/assets/16783015/fc14b2c4-e28f-41b3-8090-c115ccbeb4dc)

**Comment by pxlrbt** [comment]
See line 2 of "Problem 1": Squirephp requires extension pdo-sqlite which is not installed/enabled on your system.

**Comment by gitcoffee** [comment]
but, no exist pdo-sqlite on php8.1?


$ sudo apt-get install php8.1-sqlite3

Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete php8.1-sqlite3
E: No se pudo encontrar ningún paquete usando «*» con «php8.1-sqlite3»
E: No se pudo encontrar ningún paquete con la expresión regular «php8.1-sqlite3»

**Comment by pxlrbt** [comment]
Sorry, I don't know what exists for Ubuntu and what not
