### ISSUE TITLE
Register Resource\Pages\View as NavigationItem

### ISSUE THREAD

**Issue by e2d2-dev** [laravel-filament/demo#87]
Hi,

is there a possibilty to register/add a view of a model as navigationItem?

Something like ProfileResource but the index is the auth()->user() View and there is no table. One could use InfoList  and getRecordSubNavigation() to control a lot of entity related settings with no hassle to create custom pages.

The navigation bar postion of getRecordSubNavigation() would be nice on top/bottom as tab too.

Really big thx for all the work and effort you put in this project, it's just awesome.

sincerely, ed

**Comment by zepfietje** [comment]
Please have a look at the navigation docs on the Filament site.
