### ISSUE TITLE
DB Seeder - country & currencies seems to missing?

### ISSUE THREAD

**Issue by storeconn** [laravel-filament/demo#91]
Effects Area Customers & Orders

https://crm.storeconn.de/shop/customers

could not find driver
`SELECT * FROM "countries" WHERE "countries"."id" = mp limit 1`

`App
 \ 
Filament
 \ 
Resources
 \ 
Shop
 \ 
CustomerResource
 
: 86
App\Filament\Resources\Shop\{closure}`

**Comment by pxlrbt** [comment]
> could not find driver

That probably means you don't have SQLite extension installed.

**Comment by storeconn** [comment]
mh strange i installed/activate SQLite ext. Migrate again

ENV: We using PHP 8.3-fpm and Mysql8 as database

And still missing tables
`Illuminate
 \ 
Database
 \ 
QueryException
PHP 8.3.1
10.39.0
SQLSTATE[HY000]: General error: 1 no such table: currencies
SELECT * FROM "currencies" WHERE "currencies"."id" = bhd limit 1`

`app
 / 
Filament
 / 
Widgets
 / 
LatestOrders
.php
 
: 38`

`Tables\Columns\TextColumn::make('currency')

                    ->getStateUsing(fn ($record): ?string => Currency::find($record->currency)?->name ?? null)

                    ->searchable()

                    ->sortable(),`

**Comment by storeconn** [comment]
update i made a complete new clone and migrate new now it seems to work...strange did the exact same thing before...
