### ISSUE TITLE
instalation issue

### ISSUE THREAD

**Issue by aybinv7** [laravel-filament/demo#98]
i'm having a trouble when trying to install the project in windows cause the project requires the laravel/Horizon and  Horizon requires the " PHP's pcntl extension."
which i found on php documentation that it can not installed on Windows
![image](https://github.com/filamentphp/demo/assets/63302853/becf53d1-ba74-411d-95ec-151250357e3e)
     

any help :')

**Comment by pxlrbt** [comment]
Try running composer with `--ignore-platform-reqs`

**Comment by aybinv7** [comment]
it actually worked !! thank you
