### ISSUE TITLE
currencies migration and seeder missing

### ISSUE THREAD

**Issue by AliasSuperman** [laravel-filament/demo#99]
There is no currencies table migration or seeder

**Comment by pxlrbt** [comment]
Currencies are part of the `squirephp/currencies-en` package. There doesn't need to be a currency migration/seeder in the project.

**Comment by AliasSuperman** [comment]
But it seems to use a Currency model because going to route: /shop/customers (i.e. clicking on a customer in the index view)

Gives error:
Illuminate \ Database \ QueryException
PHP 8.2.12
10.48.3
could not find driver

select * from "countries" where "countries"."id" = kr limit 1

**Comment by pxlrbt** [comment]
Yes. It's using the currencies model from SquirePHP which uses SQLite. 

> could not find driver

Seems like you are missing SQLite driver on your system for that package.
